In [1]:
# Single Neuron

inputs = [1.0, 2.0, 3.0, 2.5]
weights = [0.2, 0.8, -0.5, 1.0]
biases = 2.0

outputs = (inputs[0] * weights[0] +
           inputs[1]* weights[1] +
           inputs[2]* weights[2] +
           inputs[3]* weights[3] +
           biases)
print(outputs)

4.8


In [2]:
# Layers of Neurons with single inputs

inputs = [1.0, 2.0, 3.0, 2.5]
weights = [[0.2, 0.8, -0.5, 1.0],
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]
biases = [2.0, 3.0, 0.5]

layers_outputs = []
for neuron_weights, neuron_bias in zip(weights,biases):
    neuron_output = 0
    for neuron_input, neuron_weight in zip(inputs, neuron_weights):
        neuron_output += neuron_input * neuron_weight
    neuron_output += neuron_bias
    layers_outputs.append(neuron_output)

print(layers_outputs)

[4.8, 1.21, 2.385]


In [3]:
import numpy as np
inputs = [1.0, 2.0, 3.0, 2.5]
weights = [[0.2, 0.8, -0.5, 1.0],
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]
biases = [2.0, 3.0, 0.5]

layers_outputs = np.dot(weights, inputs) + biases

print(layers_outputs)


[4.8   1.21  2.385]


In [4]:
a = [1,2,3]
b = [2,3,4]

output = np.dot(a,np.array(b).T)

print(output)

20


In [5]:
a = [1,2,3]
b = [2,3,4]

a = np.array([a])
b = np.array([b]).T

output = np.dot(a,b)

print(output)

[[20]]


In [6]:
a = [1,2,3]

arr = np.array([a])
# extend_arr = np.expand_dims(arr,axis=0)
extend_arr = np.expand_dims(np.array(a),axis=0)


print(extend_arr)

[[1 2 3]]


In [9]:
# Layers of Neurons with Numpy
inputs = [[1.0, 2.0, 3.0, 2.5],
          [2.0, 5.0, -1.0, 2.0],
          [-1.5, 2.7, 3.3, -0.8]]
weights = [[0.2, 0.8, -0.5, 1.0],
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]
biases = [2.0, 3.0, 0.5]

outputs = np.dot(inputs, np.array(weights).T) + biases

print(outputs)




[[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]
